# DO NOT EDIT THIS FILE!
#
# Python module FilterApp generated by omniidl

import omniORB
omniORB.updateModule("FilterApp")

# ** 1. Stub files contributing to this module
import Filter_idl

# ** 2. Sub-modules

# ** 3. End
