package FilterApp;


/**
* FilterApp/FilterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Filter.idl
* Sunday, May 9, 2021 11:23:09 PM CEST
*/

public interface FilterOperations 
{
  String applyFilter (String filtro, String imgPath);
} // interface FilterOperations
