package FilterApp;


/**
* FilterApp/Filter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Filter.idl
* Wednesday, April 21, 2021 7:51:46 PM CEST
*/

public interface Filter extends FilterOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Filter
