# DO NOT EDIT THIS FILE!
#
# Python module FilterApp__POA generated by omniidl

import omniORB
omniORB.updateModule("FilterApp__POA")

# ** 1. Stub files contributing to this module
import Filter_idl

# ** 2. Sub-modules

# ** 3. End
