package FilterApp;


/**
* FilterApp/FilterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Filter.idl
* miércoles 21 de abril de 2021 14H32' CEST
*/

public interface FilterOperations 
{
  String applyFilter (String filter, String path);
  void shutdown ();
} // interface FilterOperations
