package FilterApp;


/**
* FilterApp/Filter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Filter.idl
* miércoles 21 de abril de 2021 14H32' CEST
*/

public interface Filter extends FilterOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Filter
