package FilterApp;


/**
* FilterApp/FilterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Filter.idl
* Wednesday, April 21, 2021 8:30:48 PM CEST
*/

public interface FilterOperations 
{
  String applyFilter (String filter, String path);
  void shutdown ();
} // interface FilterOperations
